import { BabySex, NameLength, NameType } from './enums';
import { IBabiesName } from './types';

export const names: IBabiesName[] = [
    {
        id: 1,
        name: 'Laith',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 2,
        name: 'Jake',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 3,
        name: 'Lamelo',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 4,
        name: 'Abraham',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 5,
        name: 'Bartholomew',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },
    {
        id: 6,
        name: 'Noah',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 7,
        name: 'Benjamin',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 8,
        name: 'William',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 9,
        name: 'Lucus',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 10,
        name: 'Harrison',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },
    {
        id: 11,
        name: 'Selma',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 12,
        name: 'Asher',
        gender: BabySex.BOY,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 13,
        name: 'Tucker',
        gender: BabySex.BOY,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },

    {
        id: 14,
        name: 'Arya',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 15,
        name: 'Olivia',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 16,
        name: 'Fay',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 17,
        name: 'Brooklyn',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 18,
        name: 'Genevieve',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },
    {
        id: 19,
        name: 'Zoe',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 20,
        name: 'Valentina',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 21,
        name: 'Josephine',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 22,
        name: 'Maya',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 23,
        name: 'Everleigh',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },
    {
        id: 24,
        name: 'Poppy',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 25,
        name: 'Maia',
        gender: BabySex.GIRL,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 26,
        name: 'Ivy',
        gender: BabySex.GIRL,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },

    {
        id: 27,
        name: 'Jude',
        gender: BabySex.UNISEX,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 28,
        name: 'Adrian',
        gender: BabySex.UNISEX,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
    {
        id: 29,
        name: 'Sunny',
        gender: BabySex.UNISEX,
        popularity: NameType.UNIQUE,
        length: NameLength.SHORT,
    },
    {
        id: 30,
        name: 'Channing',
        gender: BabySex.UNISEX,
        popularity: NameType.TRENDY,
        length: NameLength.LONG,
    },
    {
        id: 31,
        name: 'Tennessee',
        gender: BabySex.UNISEX,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },
    {
        id: 32,
        name: 'Dallas',
        gender: BabySex.UNISEX,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },

    {
        id: 33,
        name: 'Zephyr',
        gender: BabySex.UNISEX,
        popularity: NameType.UNIQUE,
        length: NameLength.LONG,
    },

    {
        id: 34,
        name: 'Teri',
        gender: BabySex.UNISEX,
        popularity: NameType.TRENDY,
        length: NameLength.SHORT,
    },
];
